### ISSUE TITLE
Typo in Quest: "The Quests"

### ISSUE THREAD

**Issue by JustHeyo** [IamRyan30/Decursio-Team#12]
### Modpack Version

25

### Launcher Used

Prism

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

No

### Describe your issue

Quest: "The Quests" has typo in first paragraph: "begginer"; s/b "beginner".

### Log File related to your issue

n/a not a crash

### Searched for known issues?

Checked know-issues, Searched open issues

**Comment by JustHeyo** [comment]
Similar issue: Typo in quest "The Boss Fights" in paragraph "Take good care of these Eyes..." - "if you somehow manage to LOOSE one of them..." s/b "if you somehow manage to LOSE one of them" (my caps, use lowercase in final)

**Comment by JustHeyo** [comment]
Quest: Seasons and Fertility?! 0_o typo:
Paragraph 5, "beggining" s/b "beginning"; also "Glass" s/b "glass"

**Comment by IamRyan30** [comment]
Completed in PR 26.
