### ISSUE TITLE
Astral Sorcery Linking Tool Won't Craft - Not Enough Starlight

### ISSUE THREAD

**Issue by Kortako** [IamRyan30/Decursio-Team#15]
### Modpack Version

Pre-Release 27 Hotfix

### Launcher Used

Prism

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

Yes

### Describe your issue

I cannot craft the AS Linking Tool.  The starlight bar is full, I have tried with 1, 4, and even 8 fully built relays around the starlight crafting altar, it does not make a difference.  Other stuff crafts fine, such as relays and glass lenses.  I did a whole bunch of stuff in creative in a single player world to try to reproduce, and it seems to work there, so it may be a multiplayer only issue.

Here's my setup:

![2023-02-28_03 19 58](https://user-images.githubusercontent.com/5300243/221856298-7dad8761-8439-450a-a706-39c058edff8b.png)

![2023-02-28_03 20 09](https://user-images.githubusercontent.com/5300243/221856339-16242352-af5c-480b-8959-49f4ca279cb2.png)

### Log File related to your issue

[Client]: https://paste.gg/p/anonymous/f8f360ced3dd43b79fac03deb88ca8cb, [Server]: https://paste.gg/p/anonymous/d08cab5dcee44a0a8908144b8248008c, [CraftTweaker]: https://paste.gg/p/anonymous/caae17a274ca46aa8b79c53e564f0f7b

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Ha.. Ok. So.. good news, I think I now how to fix this. Bad news... a fix won't be out for the next few weeks. I might be able to rush with this update a bit tho. A fix would be for me to move all the altar recipes to Kubejs; that might fix the problem, but I'll have to check. For now, a possible fix for you, might be a server restart. Apologies for the inconvenience.
