### ISSUE TITLE
Server configs broken

### ISSUE THREAD

**Issue by bearishauto** [IamRyan30/Decursio-Team#16]
### Modpack Version

pre release 25-27(from what ive tested so far)

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

Yes

### Describe your issue

so the multiplayer server files are kind of broken as there are a ton of missing recipies and some recipes are default, tinkers table and flint tools to name a few. this kinda breaks the modpack and i hope to see it fixed soon so that this modpack is playable as intended with my friends. (i setup the server using bisect hosting)

### Log File related to your issue

.

### Searched for known issues?

Checked know-issues

**Comment by IamRyan30** [comment]
Are you using bisect's Decursio jar?

**Comment by IamRyan30** [comment]
So I just checked. Bisect has messed up the serverpack again. I'll have to write them a ticket and ask for it to be fixed. Meanwhile (and I suggest you always use this method to manage your server) you can use the custom.jar function from Bisect's server control panel. Use it with the serverpack I'm providing on curseforge. All should work fine. When you're updating the server, I recommend to make a new server with the updated serverpack, and just transfer your map over.

**Comment by IamRyan30** [comment]
The ticket is opened. I'm waiting for a response.

**Comment by IamRyan30** [comment]
Ok, finally. Two hotfixes were required for this to be solved. Apparently one of the mods that are required by the pack to be present, was blacklisted from bisect's installer. Without it present, the scripts for the custom recipes were not loaded. I tested the 2nd hotfix, `CF_ProjectDecursio_27hfa.jar` and it looks like all's fine. Thanks for reporting this.
