### ISSUE TITLE
Diet mod is broken (no nutrition bars or effects)

### ISSUE THREAD

**Issue by daodragon** [IamRyan30/Decursio-Team#17]
### Modpack Version

Pre-release 27 hotfix

### Launcher Used

FTB launcher 

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Hi, When i updated to my current version of the pack (pre-release 27 hotfix), i realized that i had none of my dietary effects happening therefore i looked at the diet tab in inventory and saw that there is no nutrition bar and it's just empty.
![Minecraft 1 16 5 - Singleplayer 3_4_2023 6_08_39 PM](https://user-images.githubusercontent.com/46076603/222932725-0016cc45-edfb-45b5-9454-536c64acc679.png)

I tried /diet reset my character or fiddle around with all the options and nothing worked but i did find out while trying to add/set my nutrition bars that all the nutrition groups (dairy, protein, etc. ) seem to not exist according the mod.

On another note, while i looked around online to find if there are pre-existing issues the only one i found is an 2 year old case where the gravestone mod caused an issue with the mod where player data weren't being convoyed properly: 
https://github.com/TheIllusiveC4/Diet/issues/40

Other than that, hope if there is any fix for my situation cus i don't want to start over my entire world just to fix that mod. 

### Log File related to your issue

I don't which log file this would be in

### Other mods

Diet mod

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Leave the `diet-groups.toml` and `diet-effects.toml` located in `The Decursio Project/defaultconfigs` here(pastebin, or gists link). Most probably your launcher failed to download all the files required by the modpack.

**Comment by daodragon** [comment]
[Dietboth.zip](https://github.com/IamRyan30/Decursio-Team/files/10892943/Dietboth.zip)
had to convert them to a zip file because it didn't allow me to paste toml file.

**Comment by IamRyan30** [comment]
> (https://pastebin.com/nLuFCw4M) Diet-Effects
> https://pastebin.com/26vKvxvJ Diet-groups
> 
> 

Ok, these look normal. What about the same files, but from this path: ```Decursio Project/saves/<your_world>/serverconfig```? Those are the files used in your world, so any problems might be related to those. Also, so you don't wait more then you have to; try to join your world where you have the diet groups missing. After that, keep the game open. Upload the ```latest.log``` file from ```Decursio Project/logs``` to pastebin. Something useful might be on it.

**Comment by daodragon** [comment]
https://pastebin.com/vMpwQgxb diet effects
https://pastebin.com/ZFSUwpa6 diet groups
[latest.log](https://github.com/IamRyan30/Decursio-Team/files/10897040/latest.log)

**Comment by IamRyan30** [comment]
Yeah ok. This should fix it. Close the game. Replace the ```diet-groups.toml``` file from serverconfigs with the file from defaultconfig. After that, start the game, join your world and the groups should be there. Unless other files are missing from the modpack, all should work.

**Comment by daodragon** [comment]
It's Working again. Thanks.
