### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by Kawisari** [IamRyan30/Decursio-Team#18]
### Modpack Version

Beta 26 and Release 27

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Today I got the same old bug as a lot on discord. The one with the brackets mostly in White with a little Green and Yellow. 
Closed Game. Restarted everything. Try to load world. After 20 min still on a black screen with the Decursio Essentials tips, I rstarted the process. After reproducing it 3 times, I updated to 27. Same problem. Stuck on the world loading screen. 

After closing the game I get the Exit Code -805306369

### Log File related to your issue

https://gist.github.com/Kawisari/5a7eca35a7739d676227a39146cdc424

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by Kawisari** [comment]
I guess reinstalling the modpack will be the easiest or are there any other options?

**Comment by IamRyan30** [comment]
Close the game. In ```Decursio Project/saves/<your_world>/serverconfig``` delete the ```woodenhopper-server.toml``` file. Start the game and try to enter your world. Let me know if that fixes the issue.

**Comment by Kawisari** [comment]
Sadly this not fixed the issue. Creating a new world works but I have 1 FPS and lags of the devil

**Comment by IamRyan30** [comment]
Leave the new log related to the world you can't enter, here.

**Comment by Kawisari** [comment]
[latest.log](https://github.com/IamRyan30/Decursio-Team/files/10899134/latest.log)

**Comment by IamRyan30** [comment]
Hmm. Ok. Try this. Close the game. Make a backup for your world. In ```Decursio Project/saves/<your_world>/serverconfig``` open the ```forge-server.toml``` file. In there, turn ```removeErroringTileEntities``` from false, to true. Save the file, open the game, try to join your world.

If this fixes the problem, move a few chunks in each direction to load the world a bit. Then close the game and return to ```forge-server.toml``` and turn ```removeErroringTileEntities``` to false again.

If this doesn't solve the issue, leave the log here.

**Comment by Kawisari** [comment]
Nothing new happened 
[latest.log](https://github.com/IamRyan30/Decursio-Team/files/10899390/latest.log)

**Comment by IamRyan30** [comment]
Well.. then try this. Close the game and delete the whole ```serverconfig``` folder in ```Decursio Project/saves/<your_world>```. Leave the log here if this doesn't work either.

**Comment by Kawisari** [comment]
It worked <3
