### ISSUE TITLE
Adding the Lightfall Mod for network support

### ISSUE THREAD

**Issue by PsalmsFighter** [IamRyan30/Decursio-Team#2]
### Modpack Version

Pre Release 22

### Problem description

Hello, I own and operate an expert-style modded Minecraft network that would like to have your pack as one of our servers. We've been working on creating the server before adding it into the network and just started adding it in. We noticed we have a log in issue where any forge server on our network above 1.12 requires an alternate solution in order to be apart of the network since both the proxy and server need to do a handshake in order to transfer the player into the modded server. The only solution we've been able to find for this is a project made by the pixelmon team called Lightfall which is a modified version of Waterfall(the proxy). Unforunately, it requires a client side mod to be installed as well for it to complete the handshake. The client side mod is also called [lightfall](https://www.curseforge.com/minecraft/mc-mods/lightfall-client).

### Suggested solution

We thought about just asking people when they first join to add this into the pack manually but thought that approach wasn't the most user friendly. We were wondering if you would consider adding the mod into the pack. [Link](https://www.curseforge.com/minecraft/mc-mods/lightfall-client)

### Alternatives considered

We could still run the server but we wouldn't be able to have the server as a part of our network if this isn't added. It would have to run standalone and wouldn't be able to have cross-server chat and other features we use.

### Additional context

Feel free to reach out through here or on Discord (Nilloc#1540) if you have any questions. Thank you for your time!

**Comment by IamRyan30** [comment]
I'll have to make this addition in the next update. I can make a hotfix version just for it, though. I'll see if I have any time to spear. How long can you wait before this is added?

**Comment by PsalmsFighter** [comment]
Thank you for reviewing it! We aren't in a big rush but sometime in the next few weeks would be amazing if possible.

**Comment by IamRyan30** [comment]
The mod was added to [Pre-Release 23](https://www.curseforge.com/minecraft/modpacks/decursio-project/files/4307840). CurseForge should approve the serverpack soon.
