### ISSUE TITLE
Rice conversion Problem

### ISSUE THREAD

**Issue by daodragon** [IamRyan30/Decursio-Team#20]
### Modpack Version

Pre-release 27 hotfix

### Launcher Used

FTB launcher 

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Rice from pam's harvest craft can be stored as rice bale (9x). however converting back from rice bale allows for both rice from pam and rice panicle from farmer delight with a priority to farmer delight rice panicle (first option it shows you). meaning if you accidently just back convert without realizing it is rice from the farmer delight you are left with an item that has no usage. Rice panicle has no usage in the jei and can't even be converted back to a rice bale. I haven't even been able to planet them on rich soil nor water. 

### Log File related to your issue

Recipe problem?

### Other mods

pam's harvest craft
Farmer's delight

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Got it, I'll look into it.

**Comment by IamRyan30** [comment]
Will be fixed in r1.0.0.
