### ISSUE TITLE
some stuff wrong with bees searching

### ISSUE THREAD

**Issue by alucold** [IamRyan30/Decursio-Team#22]
### Modpack Version

pre release 27.zip

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only, Did not test on Singleplayer, I will do that now

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

so basically in the JEI im trying to search up how to breed the bees but when i search up the bees and then right click or left click nothing appears. like nothing at all. and then i make the beepedia to see if i can find the breeding stuff in there. so I go make it and then right click it. crashes my minecraft but my server doesnt crash, the server is completely fine. it crashes me saying there is no mod that says it causes it. its similar to what happened to when i pressed f5 when i shrunk using the shrink mod on what i saw when i crashed. Also when clicking right click on any of the honeycubes it doesnt show its uses in the centrifuge at all because i remember thats what you would put the honey combs into.

### Log File related to your issue

https://bytebin.lucko.me/ROL9r5DRPG

### Crash Report

https://bytebin.lucko.me/ROL9r5DRPG

### Searched for known issues?

I did not search

**Comment by IamRyan30** [comment]
Both of those are the crash file. I would've needed the log file from your client. Also, how did you manage to make the beepedia? It's disabled. It's disabled for this exact reason. Did you update the server properly to the 27th version? You're owner of the server?

**Comment by alucold** [comment]
> Both of those are the crash file. I would've needed the log file from your client. Also, how did you manage to make the beepedia? It's disabled. It's disabled for this exact reason. Did you update the server properly to the 27th version? You're the owner of the server?

I reuploaded the files to update my server again and it fixed the problem guess something went wrong when updating and it still worked fine without some stuff. also for the beepedia i was able to craft it because the crafting recipe was in the book (fifty shades of bee and i did it. (btw this was before I reuploaded the files) and i tried to make it again after i fixed the issue and the recipe still works.

**Comment by IamRyan30** [comment]
Oh, apparently yeah, the Beepedia recipe is still there. I fixed it now, thanks.
