### ISSUE TITLE
Zombie+rats/cockroachs=Lag

### ISSUE THREAD

**Issue by daodragon** [IamRyan30/Decursio-Team#23]
### Modpack Version

Pre-release 27 hotfix

### Launcher Used

FTB launcher 

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Basically Monster's are hostile to rats/coackroachs, this by itself is fine. However, zombie pickup any item on the ground including rat's drop like skin or flesh and because mobs don't despawn if they are holding items nor contribute to the mob cap anymore, it causes an infestation that lags the world beyond belief. It doesn't help that rats and cockroaches spawn in dark place and basically share living space with zombies. I had to kill atleast 48 zombies and i know that for a fact cus of all the rat/cockroachs loot i picked up. 1 rat hand + 17 flesh + 7 skin + 3 skull + 18 cockroach wing. (cokroaches might have also been killed by the centipedes which spawn in the dark and have their drop picked up by zombies).
![Minecraft 1 16 5 - Singleplayer 3_8_2023 11_35_03 PM](https://user-images.githubusercontent.com/46076603/223918371-0c8cd0c8-6165-4bd1-b439-c2bac3ece2c6.png)
I just wanted to you know about this cause this can negatively impact someone's base if they are not aware on what's underground. the only reason i realize this was because when i tried to go down to mine i saw that minimap was full of zombie icons everywhere.

### Log File related to your issue

-

### Crash Report

-

### Other mods

Rats
Alex's mob
Vanilla Minecraft mechanics

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
I could try to add Let Me Despawn, but I'm afraid ImprovedMobs might interfere with it, in some way. I'll have to run some tests.

**Comment by daodragon** [comment]
" The mod prevents a mob from gaining persistent tag on item pickup. If the mob generates or spawns in with the tag on it it will not despawn. Only the mobs that spawned without a persistent tag that later pick up items despawn." From the mod author of Let me despawn. I am not sure that ImprovedMobs spawn with a persistence tag, as that would insinuate that they will also not despawn even if they haven't picked up an item and i have not seen that happening.
