### ISSUE TITLE
QoL/Decorative Mods

### ISSUE THREAD

**Issue by XeramHosting** [IamRyan30/Decursio-Team#29]
### Modpack Version

Pre-Release 27

### Problem description

There's a few things here so I'll list their suggested solutions in the same order.

 - Alternative fluid transportation
 - Lack of "good" automation
 - Limited base navigation.
 - Limited light variants
 - No long distance storage transfer

### Suggested solution

 - Pretty Pipes: Fluid (https://www.curseforge.com/minecraft/mc-mods/pretty-pipes-fluids)
 - Xnet (https://www.curseforge.com/minecraft/mc-mods/xnet)
 - Travel Anchors (https://www.curseforge.com/minecraft/mc-mods/travel-anchors)
 - Simply Light (https://www.curseforge.com/minecraft/mc-mods/simply-light)
 - Ender Storage (https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)

### Alternatives considered

 - N/A 
 - Integrated Dynamics (https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics)
 - Openblocks Elevator (https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
 - N/A
 - DimStorage (https://www.curseforge.com/minecraft/mc-mods/dimstorage)

### Additional context

I'll go ahead and break down my reason here, using the same format as above.

 - Given that Pretty Pipes is in the pack and it seems to be the "best" item transportation method during Age 2 I believe adding the fluid variants would make a nice addition. These pipes aren't extremely over powered and work similarly to the ones already available in Age 2. This would allow players using Pretty Pipes as their main item transport method to keep something in a similar style whilst not completely negating the pipes from IE or Create.

 - Unless I'm completely missing something there's not many good automation methods in this pack, especially when it comes to more obscure setups. Adding a mod such as XNet or ID will allow for automation past the basics offered by the existing mods, this also allows for cleaner setups and matches the tone of progression seen throughout the rest of the pack. Starting from a caveman like feel to going to the stars and seemingly becoming a God. IMO it doesn't make much sense that we can become so technically advanced yet not having a good way of managing said tech.

 - This suggestion is definitely more of a QoL suggestion. As far as I can tell there's no transportation method that allows for quick movement around a base. The addition of Travel Anchors would allow players to set "hotspots" around their base that they can quickly get to, if this seems too excessive then something simpler such as openblock elevators fits well with the theme. Elevators will allow for quicker vertical movement in bases, allowing more verticality in builds as well.

 - This one's simple, just like the mod name suggests! Simply Light adds a few variations of a more modern looking light system. This is definitely the most personal suggestion as I just don't like the other light solutions in the pack much.
 
 - Like the first couple suggestions this one is something that I don't see how it isn't already part of the progression. AE2 long-range wireless storage is a nightmare unless you're running a super long line of cable. This is slightly remedied through the use of Entangled, but having too many entangled blocks is very expensive and starts chewing at performance quickly. Considering we have the technology to move energy around wirelessly and access machines from an infinite range in the overworld it would make sense that we have simpler methods of transporting both items and fluid. Ender Storage is normally the default in 1.16, however I find DimStorage to be a great alternative and my own personal preference.
 
 Side note: I remember that quantum entangloporters exist after writing that last section, however, these still do not remedy the issue I see which is a simple and quick way of moving items/fluid in a basic manner. The QE seems to be a much more advanced piece of tech in comparison.
 
 
Please let me know if there's any questions or concerns with any of the suggestions. I don't expect most, if any, to get approved/implemented but I figured it wouldn't hurt to throw it out there. Thanks for hearing me out!

**Comment by IamRyan30** [comment]
Thanks for taking the time to write all of this, but unfortunately I'm not interested in most of these. They've been suggested before and I also didn't want them at that time (Simply Lights is an exception). I'll try to add it in the next update, but that might be long time from now. The pack is near its end. All the features added in the last updates, have been either very easy to implement, or planned for a really long time.

- Pretty Pipes: apologies but there's no reason someone would use the pipes from create or ie if they have access to those.
- Xnet: I like to know how the mods added in the pack, works. I have no experience with xnet or id, and I don't have time to learn them rn.
- I don't wanna provide such an option. I'd like to force the players to make interesting designs for their elevators/teleporters.
- I'd like to add Simple Lights.
- Even if I added Ender Store, I'd give it an insane recipe. I don't want to provide easy access to wireless transportation. And I've never heard of DimStorage until now.

**Comment by Tazmondo** [comment]
@XeramHosting Just wanted to chip in since I also thought the exclusion of mods like XNet was a bit weird.

I've found that having to automate with more primitive solutions has been pretty fun. Almost every pack these days ships with XNet or Integrated Dynamics, and it makes just those two mods the go-to for most automations, and honestly it got a bit boring. Being forced to use lesser known things, like some of Botania's redstone additions, or the Immersive Engineering logic units, and actually just use redstone itself (for the first time in a while), has been a pretty refreshing experience.
