### ISSUE TITLE
Unable to set the Tinker's seared filtered drain to "andesite alloy" fluid

### ISSUE THREAD

**Issue by guvnor33** [IamRyan30/Decursio-Team#31]
### Modpack Version

25

### Launcher Used

GDLauncher

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

Yes

### Describe your issue

I want to set the filtered seared drain to liquid andesite alloy but I am unable to do so because there is not a valid and usable liquid container available with which to set the filter.

### Log File related to your issue

none

### Searched for known issues?

Checked know-issues

**Comment by Tazmondo** [comment]
Try using these copper cans, you can easily fill it by right clicking the regular drain with the alloy set as the bottom fluid.

![image](https://user-images.githubusercontent.com/29681369/226111906-fd91711c-91f8-49cc-a3a3-0acd7418c069.png)

**Comment by IamRyan30** [comment]
Yeah, if the can works (it should), I'll have this issue closed.

**Comment by guvnor33** [comment]
Yes, I understand that it is the copper cans that are used to set the filter. I have tried ALL containers. I have cheated them all to myself, in an effort to experiment, filled with this liquid. It is the filter (filtered seared drain) that is refusing to be set to this liquid.

**Comment by IamRyan30** [comment]
> Yes, I understand that it is the copper cans that are used to set the filter. I have tried ALL containers. I have cheated them all to myself, in an effort to experiment, filled with this liquid. It is the filter (filtered seared drain) that is refusing to be set to this liquid.

Wait. Seared Drain? U mean the Seared Duct.

**Comment by IamRyan30** [comment]
Probably an user error. Use the Seared Duct.
