### ISSUE TITLE
Pendorite not appearing in JEI

### ISSUE THREAD

**Issue by tapegreen** [IamRyan30/Decursio-Team#33]
### Modpack Version

1.0.1

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Pendorite does not appear in JEI (currently in age 2). Doesn't say "unknown item". Found under y-level 15, in Embur Bog biome.

### Log File related to your issue

NONE

### Searched for known issues?

Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
There are multiple minerals which can be found. The should've been removed from the world gen, but at that time, I had no idea how to do it. The bug it's the fact that you managed to obtain it.
