### ISSUE TITLE
Brass Encased Jet - Unable to Produce using Mechanical Crafting

### ISSUE THREAD

**Issue by TechIdeations** [IamRyan30/Decursio-Team#34]
### Modpack Version

r1.0.1

### Launcher Used

CurseForge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

Yes

### Summary
I, alongside [OminousWo1f](https://i.imgur.com/Zv8DLCz.png) were unable to produce the **Brass Encased Jet** using **Mechanical Crafters** in a **5x5 Grid**; initiated using a button placed on the bottom-right side of the grid. 

### Environment Scene 
![image](https://user-images.githubusercontent.com/92654732/226479429-e620dee7-8b6d-4fab-ba5f-2d8f5744886e.png)

### Scene Result
![image](https://user-images.githubusercontent.com/92654732/226480842-f3adef4e-2201-4706-a00d-ebe92355d75b.png)

### Ingredients Used
![image](https://user-images.githubusercontent.com/92654732/226480927-c5c536a2-751f-478d-a5bb-1f7695305df2.png)

### Log File related to your issue

http://no-log.com

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
The log file is not available. Did you try to remove the empty crafters? Does this persist in r1.0.2?

**Comment by Lopezak** [comment]
> The log file is not available. Did you try to remove the empty crafters? Does this persist in r1.0.2? Have you tried to make this recipe with a new Exoskeleton? One that doesn't have nbt data to it.

I did try it out in 1.0.2 in creative mode so all the items were not worn and pulled directly from the creative inventory

**Comment by IamRyan30** [comment]
I still need the log and, if possible, the kubejs server log. That's in `logs/kubejs/server.txt`. The fix might be an easy one, but those logs might be useful anyway.

**Comment by Lopezak** [comment]
> I still need the log and, if possible, the kubejs server log. That's in `logs/kubejs/server.txt`. The fix might be an easy one, but those logs might be useful anyway.

[logs.zip](https://github.com/IamRyan30/Decursio-Team/files/11033573/logs.zip)


That's everything from my Singleplayer testing that I did. The last time I logged into it was when I ran the tests. Hopefully that's everything you need

**Comment by IamRyan30** [comment]
Ok. Here's the fix:
```
	e.custom({
		type: 'create:mechanical_crafting',
		pattern: [
			'G   G',
			'BGFGB',
			'DCACD',
			'GECEG',
			' EAE ',
		],
		key: {
			'A': Ingredient.of('create:precision_mechanism').toJson(),
			'B': Ingredient.of('create:cogwheel').toJson(),
			'C': Ingredient.of('create:brass_casing').toJson(),
			'D': Ingredient.of('create:encased_fan').toJson(),
			'E': Ingredient.of('#forge:ingots/brass').toJson(),
			'F': Ingredient.of('create_stuff_additions:exoskeleton_chestplate').ignoreNBT().toJson(),
			'G': Ingredient.of('#forge:plates/brass').toJson(),
		},
		result: Item.of('create_stuff_additions:encased_jet_chestplate').toResultJson(),
		acceptMirrored: false
	}).id('kubejs:create/mechanical_crafting/brass_jetplate')
```

The recipe needs to ignore the nbt data for the exoskeleton. It just needs the `.ignoreNBT()` part. I won't have this fixed for some time unfortunately. Apologies for the inconveniance.

**Comment by TechIdeations** [comment]
Apologies on the logs, I was unable to upload due to some problems on my end that I just resolved now but see that it was all worked out!
