### ISSUE TITLE
Duplicate lumium gear recipe

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#36]
### Modpack Version

r1.0.2

### Launcher Used

Prism

### Did this issue occur on Multiplayer, Singleplayer, or both?

Did not test on Singleplayer, I will do that now

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

No

### Describe your issue

There are two recipes for lumium gears in the multiservo press.

They both have slightly different energy values as well.

![image](https://user-images.githubusercontent.com/29681369/226737431-fc153dda-42fb-4257-9090-4ca17329b2ae.png)
![image](https://user-images.githubusercontent.com/29681369/226737458-1c06e95a-056f-42ad-98df-747b366178d5.png)

### Log File related to your issue

not relevant

### Other mods

Just Enough Calculation

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Fixed in r1.0.4
