### ISSUE TITLE
Certuz quartz charger typo

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#39]
### Modpack Version

R1.0.2

### Launcher Used

Prism

### Did this issue occur on Multiplayer, Singleplayer, or both?

Did not test on Singleplayer, I will do that now

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

No

### Describe your issue

Typo in name of the Certuz Quartz Charger.

![image](https://user-images.githubusercontent.com/29681369/227242959-94ab114e-36e3-4cda-9f4e-32acf732700e.png)

### Log File related to your issue

not relevant

### Other mods

Just Enough Calculation

### Searched for known issues?

Checked know-issues, Checked faq, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Fixed in r1.0.4
