### ISSUE TITLE
Crash when retrieving diesel from the coker using a bucket

### ISSUE THREAD

**Issue by guvnor33** [IamRyan30/Decursio-Team#40]
### Modpack Version

25

### Launcher Used

GDLauncher

### Did this issue occur on Multiplayer, Singleplayer, or both?

Singleplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

No

### Describe your issue

When I place an empty bucket into the coker to remove some diesel the game crashes to the crash report screen. I have reproduced it twice.

### Log File related to your issue

na

### Crash Report

https://pastebin.com/JPAx21kb

### Searched for known issues?

Checked know-issues

**Comment by IamRyan30** [comment]
It this is a bug in IE, that's something they would have to fix. I'll try to test it and see if this happens only with IE.

**Comment by IamRyan30** [comment]
Fixed in r1.0.4
