### ISSUE TITLE
Add an automatable recipe for resonating gems

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#43]
### Modpack Version

r1.0.4

### Problem description

There is no way to automate the AS starlight infuser in this pack. Create deployer does not work.

Resonating gems are used to craft sparks, which are then used in a bunch of other different recipes, as well as being useful in their own right for tons of Botania setups.

### Suggested solution

Add a recipe for them, e.g. using the botania elven portal or a rune altar recipe. It could be more expensive as a tradeoff for the automation.

### Alternatives considered

Remove them from the spark recipe.
A lot of their other crafts are unlikely to be needed in large amounts, so this would probably be fine.
I think it'd be better to just add an alternative recipe for them, just in case they are needed in large amounts.

**Comment by Tazmondo** [comment]
I had a deployer placing acacia logs for a latex setup also within claimed chunks which worked fine, would I have needed extra configuration to get this working? I also didn't have any minecolonies near enough to interfere.

I thought that the reason why it didn't work is that the deployer fake player didn't have the astral knowledge needed to be able to use the resonating wand on the infuser, so I'm surprised it worked for you - maybe it only works in creative worlds or something?

**Comment by IamRyan30** [comment]
Yeah, I got it. I assumed the problem was inserting aquamarine into the Infuser. I'll have an update up this week. Probably add an Elven Trade for the Resonating gem.

**Comment by SheReyy** [comment]
Fixed in 1.0.5
