### ISSUE TITLE
Reconsider rod of the lands recipe

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#44]
### Modpack Version

r.1.0.4

### Problem description

The rod of the lands is completely unfeasible to craft, at least in age 2 when it is unlocked.

It requires 2 5x compressed dirt blocks. This is equivalent to 118,098 dirt.

I feel like this is an oversight, as it doesn't really make sense for an item like this to be so expensive, especially with no easy way to automate the production of dirt at this point in the game.

### Suggested solution

Change the recipe to require 2x compressed dirt (160 dirt blocks).

### Alternatives considered

Using 4x compressed would require 13000 dirt, which is still unfeasible.
3x would mean getting 1500 dirt, which is doable, and may be more in the spirit of an expert pack than 2x or 1x.

**Comment by IamRyan30** [comment]
I'll consider this for the next version.

**Comment by SheReyy** [comment]
Now it will be a 3x compressed dirt.
