### ISSUE TITLE
Re-enable AE2 Color Applicator

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#45]
### Modpack Version

r1.0.4

### Problem description

The AE2 color applicator is disabled. (In age 3 at least, I cannot see the recipe)
It's an extremely useful tool for managing AE2 networks.

[The wiki also doesn't state this under modifications to AE2](https://wiki.decursioteam.com/modpacks/decursio-project-expert/general-info/modified-features-wip#applied-energistics-2)

### Suggested solution

Re-enable the recipe

### Alternatives considered

Re-enable the recipe but make it harder

**Comment by IamRyan30** [comment]
I'll make it available again. I don't remember why it was removed.

**Comment by SheReyy** [comment]
Fixed in 1.0.5
