### ISSUE TITLE
Cannot craft flat ME interface back into block form

### ISSUE THREAD

**Issue by Tazmondo** [IamRyan30/Decursio-Team#46]
### Modpack Version

r1.0.4

### Launcher Used

Prism

### Did this issue occur on Multiplayer, Singleplayer, or both?

Did not test on Singleplayer, I will do that now

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

No

### Describe your issue

There should be a recipe to convert ME interfaces back into block form from their panel/flat version.

However trying to do this craft yields no result in the crafting table.

This could be a problem with AE2, but I figured it's more likely to be a modpack issue considering the huge number of crafting changes there are.

### Log File related to your issue

not relevant

### Searched for known issues?

Checked Modified Features, Checked GUI & Visuals, Checked Gameplay, Searched open issues, Searched closed issues

**Comment by SheReyy** [comment]
Fixed in 1.0.5
