### ISSUE TITLE
Uncraftable item

### ISSUE THREAD

**Issue by IcyOceans** [IamRyan30/Decursio-Team#49]
### Modpack Version

 Decursio Project Expert 1.16.5

### Launcher Used

curse forge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Both

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

Yes

### Describe your issue

Trapped chest is an uncraftable item in the modpack and can only be found in rare world generation areas.
would like to know why it is not craftable if there is a reason.
It is needed in mine colonies to build the courier lvl 4.
Thanks

### Log File related to your issue

N/A

### Searched for known issues?

Checked Modified Features, Checked GUI & Visuals, Checked Gameplay, Searched open issues, Searched closed issues, I did not search

**Comment by IamRyan30** [comment]
Yeah, I can confirm that's the case. It's not intended. Unfortunately, it won't be fixed for some time.

**Comment by SheReyy** [comment]
Fixed in 1.0.5
