### ISSUE TITLE
Pre-Release 25 needs forge 36.2.34 but ships with 36.2.33

### ISSUE THREAD

**Issue by Goobaroo** [IamRyan30/Decursio-Team#5]
### Modpack Version

Pre-Release 25

### Launcher Used

server install

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

Yes

### Describe your issue

Server startup throws errors about incompatibilities of some of the mods with the version of forge included.

Changing the start.sh script to pull 36.2.34 fixes the issue.

```
[20Jan2023 09:09:46.194] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mod §ejeimultiblocks§r requires §6forge§r §o36.2.34 or above§r
§7Currently, §6forge§r§7 is §o36.2.33,
	Mod §ecomputercraft§r requires §6forge§r §o36.2.34 or above, and below 37§r
§7Currently, §6forge§r§7 is §o36.2.33
```

### Log File related to your issue

none

### Searched for known issues?

Checked know-issues, Searched open issues, Searched closed issues

**Comment by Lopezak** [comment]
Just curious, was this a fresh install or an update from a previous version?

**Comment by IamRyan30** [comment]
Yeah, I updated forge a few versions ago, but I forgot to change the linux file. I'll have a new serverpack uploaded shortly. Thanks.
