### ISSUE TITLE
Iridescent Package Crafting Altar destroyed upon mining

### ISSUE THREAD

**Issue by MCaesar** [IamRyan30/Decursio-Team#51]
### Modpack Version

r.1.0.4

### Launcher Used

Curseforge

### Did this issue occur on Multiplayer, Singleplayer, or both?

Both

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Mined the Astral altar packager, didn't get the item back. Tried multiple pickaxes thinking it was the pick I was using or mining level, but every attempt destroyed it without giving the item back.

### Log File related to your issue

https://pastebin.com/BqEf3BLg

### Searched for known issues?

Checked Modified Features, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment]
Yeah, I'll have this fixed in r1.0.5

**Comment by SheReyy** [comment]
Fixed in 1.0.5
