### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by evilspacebunny** [IamRyan30/Decursio-Team#53]
### Modpack Version

r1.0.5

### Launcher Used

Curse

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

It's in a village, I know that much not sure what else could be causing it. If I'm able to reset the player. Maybe a conflict between quark and alex mobs? 

### Log File related to your issue

https://pastebin.com/sSCpVwen

### Searched for known issues?

Searched closed issues

**Comment by SheReyy** [comment]
Looks like a problem with Charm and a Villager following a player with an Emerald Block in their hand. You could try to make a backup, then start the server with forge's `removeErroringEntities` feature on true. You can find it in your world's `serverconfig` folder, in `forge-server.toml`. Make sure to turn it off after using it.

**Comment by evilspacebunny** [comment]
I did try that as well as removeErroringTileEntities but neither helped.  I also set the max tick time to -1 to disable the watch dog. It's one of the reasons why I'm here as I've never seen a crash like this before in all my years lol.  Tried a kill command but that area isn't loaded and it crashes as soon as someone gets close.

**Comment by SheReyy** [comment]
Try to disable the `VillagersFollowEmeraldBlocks enabled` feature in `charm-common.toml`.

**Comment by evilspacebunny** [comment]
That seemed to be the issue! If it does happen again after it's disabled I'll keep you posted. Thank you so much :D
