### ISSUE TITLE
The server crashed

### ISSUE THREAD

**Issue by Xure1** [IamRyan30/Decursio-Team#6]
### Modpack Version

Ex:25

### Launcher Used

Ex:Curseforge multiplayer

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only

### Do you, or did you had Optifine installed when the issue took place?

Yes

### Tried reproducing without Optifine?

Yes

### Describe your issue

When i used the Reaper's Scythe to ignite Nether Porta,The server was crashed.

### Log File related to your issue

https://github.com/Xure1/crash/blob/main/debug-2.log.gz

### Crash Report

https://github.com/Xure1/crash/blob/main/crash%20report

### Searched for known issues?

Checked know-issues

**Comment by IamRyan30** [comment]
You're using forge 36.2.39. We're using 36.2.34. Downgrade.

**Comment by Xure1** [comment]
i try to downgrade my forge, But there is another crash happend
Link:https://github.com/Xure1/crash/blob/main/crash2

**Comment by Xure1** [comment]
I also can give you logs
link:https://github.com/Xure1/crash/blob/main/2023-01-27-1.log.gz

**Comment by IamRyan30** [comment]
Make a world backup. Then, try to remove Alex's Mobs, then join the server. If it starts normally, close it, reinstall the mod and you should be good.

**Comment by Xure1** [comment]
I removed Alex's Mobs,But server crashed again
link:https://github.com/Xure1/crash/blob/main/crash3

**Comment by IamRyan30** [comment]
You're using Java 17. 1.16 uses java 8.

**Comment by Xure1** [comment]
crashed again
Link:https://github.com/Xure1/crash/blob/main/crash4

**Comment by IamRyan30** [comment]
Hmm. You're using a plugin called Arclight. Is this intentional? If it's not, remove it. Apparently it interferes with the Roadrunner mod. Before starting the server I'd also go to the `world/serverconfig/forge-server.toml` file and set `removeErroringEntities` from false to true. After that, start the server. Then, shut it down, set `removeErroringEntities` from true, to false, then your server should be good to go.

**Comment by Xure1** [comment]
I used this server core to optimize my server with some plugins, Do you hava any the other server core?

**Comment by IamRyan30** [comment]
Unfortunately not. You can try to remove roadrunner and play with the other optimization mods we're using, but I don't recommend that. I'm generally not familiar with any kind of plugins.

**Comment by Xure1** [comment]
I see,Thanks for you help.
